name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: test
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gsutil
        with:
          args: cp test.txt gs://lantern-builds/${{ github.ref }}/${{ github.run_number }}/test.txt
